/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.sudplan.wupp.objecteditors;

import Sirius.navigator.connection.SessionManager;
import Sirius.navigator.ui.ComponentRegistry;

import Sirius.server.middleware.types.MetaClass;
import Sirius.server.middleware.types.MetaObject;

import org.jdesktop.swingx.JXErrorPane;
import org.jdesktop.swingx.error.ErrorInfo;

import org.openide.util.NbBundle;
import org.openide.util.WeakListeners;

import java.util.Collection;
import java.util.logging.Level;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;

import de.cismet.cids.custom.sudplan.AbstractCidsBeanRenderer;
import de.cismet.cids.custom.sudplan.SMSUtils;
import de.cismet.cids.custom.sudplan.wupp.DeltaConfigurationListWidged;

import de.cismet.cids.dynamics.CidsBean;

import de.cismet.cids.editors.EditorClosedEvent;
import de.cismet.cids.editors.EditorSaveListener;

import de.cismet.cids.navigator.utils.ClassCacheMultiple;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  $Revision$, $Date$
 */
public class DeltaConfigurationEditor extends AbstractCidsBeanRenderer implements EditorSaveListener {

    //~ Instance fields --------------------------------------------------------

    private final transient boolean editable;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkLocked;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblLinkedBreakingEdges;
    private javax.swing.JLabel lblLinkedBreakingEdgesValue;
    private javax.swing.JLabel lblLocked;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextArea txaDescription;
    private javax.swing.JTextField txtName;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form DeltaConfigurationEditor.
     */
    public DeltaConfigurationEditor() {
        this(true);
    }

    /**
     * Creates a new DeltaConfigurationEditor object.
     *
     * @param  editable  DOCUMENT ME!
     */
    public DeltaConfigurationEditor(final boolean editable) {
        this.editable = editable;
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescription = new javax.swing.JTextArea();
        lblLocked = new javax.swing.JLabel();
        chkLocked = new javax.swing.JCheckBox();
        lblLinkedBreakingEdges = new javax.swing.JLabel();
        lblLinkedBreakingEdgesValue = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        lblName.setText(NbBundle.getMessage(DeltaConfigurationEditor.class, "DeltaConfigurationEditor.lblName.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblName, gridBagConstraints);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${cidsBean.name}"),
                txtName,
                org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue("<not set>");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtName, gridBagConstraints);

        lblDescription.setText(NbBundle.getMessage(
                DeltaConfigurationEditor.class,
                "DeltaConfigurationEditor.lblDescription.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblDescription, gridBagConstraints);

        txaDescription.setColumns(20);
        txaDescription.setRows(5);
        txaDescription.setMinimumSize(new java.awt.Dimension(0, 50));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${cidsBean.description}"),
                txaDescription,
                org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue("<not set>");
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(txaDescription);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jScrollPane1, gridBagConstraints);

        lblLocked.setText(NbBundle.getMessage(
                DeltaConfigurationEditor.class,
                "DeltaConfigurationEditor.lblLocked.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblLocked, gridBagConstraints);

        chkLocked.setText(NbBundle.getMessage(
                DeltaConfigurationEditor.class,
                "DeltaConfigurationEditor.chkLocked.text")); // NOI18N
        chkLocked.setContentAreaFilled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${cidsBean.locked}"),
                chkLocked,
                org.jdesktop.beansbinding.BeanProperty.create("selected"));
        binding.setSourceNullValue(false);
        binding.setSourceUnreadableValue(false);
        bindingGroup.addBinding(binding);

        chkLocked.addItemListener(new java.awt.event.ItemListener() {

                @Override
                public void itemStateChanged(final java.awt.event.ItemEvent evt) {
                    chkLockedItemStateChanged(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(chkLocked, gridBagConstraints);

        lblLinkedBreakingEdges.setText(NbBundle.getMessage(
                DeltaConfigurationEditor.class,
                "DeltaConfigurationEditor.lblLinkedBreakingEdges.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblLinkedBreakingEdges, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblLinkedBreakingEdgesValue, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jSeparator1, gridBagConstraints);

        jPanel1.setOpaque(false);

        final org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(0, 369, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(0, 124, Short.MAX_VALUE));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.8;
        add(jPanel1, gridBagConstraints);

        bindingGroup.bind();
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void chkLockedItemStateChanged(final java.awt.event.ItemEvent evt) { //GEN-FIRST:event_chkLockedItemStateChanged
        if (cidsBean != null) {
            final Boolean locked = (Boolean)cidsBean.getProperty("locked");
            if (locked != null) {
                chkLocked.setSelected(locked.booleanValue());
            } else {
                chkLocked.setSelected(false);
            }
        }
    }                                                                            //GEN-LAST:event_chkLockedItemStateChanged

    @Override
    protected void init() {
        bindingGroup.unbind();
        bindingGroup.bind();

        final Collection edges = (Collection)cidsBean.getProperty("delta_breaking_edges");
        // list size cannot be bound
        lblLinkedBreakingEdgesValue.setText((edges == null) ? "0" : String.valueOf(edges.size()));

        // NOTE: maybe they want to edit the description and name anyway
        final Boolean locked = (Boolean)cidsBean.getProperty("locked"); // NOI18N
        if (((locked != null) && locked) || !editable) {
            txtName.setEditable(false);
            txaDescription.setEditable(false);
        } else {
            txtName.setEditable(true);
            txaDescription.setEditable(true);
        }
    }

    @Override
    public void editorClosed(final EditorClosedEvent event) {
        // noop
    }

    @Override
    public boolean prepareForSave() {
        try {
            final CidsBean configToCheck = reloadConfiguration(cidsBean);

            final Boolean locked = (Boolean)configToCheck.getProperty("locked");

            if (locked == null) {
                throw new IllegalStateException("cannot check the locked state from the delta configuration");
            }

            if (locked.booleanValue()) {
                JOptionPane.showMessageDialog(
                    this,
                    "Die ausgewählte Änderungskonfiguration wurde gesperrt! Das Speichern ist nicht möglich.",
                    "Speichern Fehlgeschlagen",
                    JOptionPane.ERROR_MESSAGE);

                return false;
            }
        } catch (Exception ex) {
            JXErrorPane.showDialog(
                this,
                new ErrorInfo(
                    "Fehler beim Überprüfen",
                    "Beim Überprüfen auf Sperrung der Änderungskonfiguration ist ein Fehler aufgetreten.",
                    null,
                    "EDITOR",
                    ex,
                    Level.WARNING,
                    null));

            return false;
        }

        final Integer investID = (Integer)cidsBean.getProperty("original_object.investigation_area.id");
        ComponentRegistry.getRegistry()
                .getCatalogueTree()
                .requestRefreshNode("wupp.investigation_area." + investID + ".config");
        DeltaConfigurationListWidged.getInstance().fireConfigsChanged();

        return true;
    }

    /**
     * DOCUMENT ME!
     *
     * @param   deltaConfig  DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     *
     * @throws  IllegalStateException  DOCUMENT ME!
     */
    public CidsBean reloadConfiguration(final CidsBean deltaConfig) {
        try {
            if ((deltaConfig == null)) {
                throw new IllegalStateException(
                    "delta configuration cannot be null");
            }
            final MetaClass mc = ClassCacheMultiple.getMetaClass("SUDPLAN-WUPP", "delta_configuration");   // NOI18N
            if (mc == null) {
                throw new IllegalStateException(
                    "illegal domain for this operation, mc 'delta_configuration@SUDPLAN-WUPP' not found"); // NOI18N
            }

            final Integer id = (Integer)cidsBean.getProperty("geocpm_configuration_id.id");         // NOI18N
            if (id == null) {
                throw new IllegalStateException("cannot get geocpm configuration id: " + cidsBean); // NOI18N
            }

            final Integer deltaId = (Integer)deltaConfig.getProperty("id");
            if (deltaId == null) {
                throw new IllegalStateException("cannot get delta configuration id: " + deltaConfig);
            }

            final String query = "select " + mc.getID() + "," + mc.getPrimaryKey() + " from " // NOI18N
                        + mc.getTableName()
                        + " where original_object = " + id
                        + " AND id = " + deltaId;                                             // NOI18N

            final MetaObject[] deltaCfgObjects = SessionManager.getProxy()
                        .getMetaObjectByQuery(SessionManager.getSession().getUser(),
                            query,
                            SMSUtils.DOMAIN_SUDPLAN_WUPP);

            if ((deltaCfgObjects == null) || (deltaCfgObjects.length <= 0) || (deltaCfgObjects.length > 1)
                        || (deltaCfgObjects[0] == null)) {
                throw new IllegalStateException(
                    "cannot reload, because there is no configuration or more than one are found: "
                            + deltaConfig);
            }

            final MetaObject mo = deltaCfgObjects[0];
            final CidsBean configToCheck = mo.getBean();

            return configToCheck;
        } catch (final Exception ex) {
            final String message = "cannot check for locked state from selected delta configuration"; // NOI18N
            throw new IllegalStateException(message, ex);
        }
    }

    /**
     * Adds the given {@link DocumentListener} object to the name text field's document. However, the listener is not
     * added directly, but a weak listener is created and added. Thus the caller of this operation is obliged to keep a
     * strong reference to the listener object. Otherwise it will be garbage collected. For this reason there is no
     * 'remove' operation, because this will happen implicitly if the listener reference is thrown away. Moreover it is
     * not possible to identify the weak listener reference anyway.
     *
     * @param  docL  DOCUMENT ME!
     */
    public void addNameChangeListener(final DocumentListener docL) {
        txtName.getDocument().addDocumentListener(WeakListeners.document(docL, txtName.getDocument()));
    }
}
