/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.sudplan.wupp;

import java.awt.EventQueue;

/**
 * DOCUMENT ME!
 *
 * @author   jlauter
 * @version  $Revision$, $Date$
 */
public class DeltaSurfacePreparePanel extends javax.swing.JPanel {

    //~ Instance fields --------------------------------------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form DeltaSurfacePreparePanel.
     *
     * @param  maxValue  DOCUMENT ME!
     */
    public DeltaSurfacePreparePanel(final int maxValue) {
        initComponents();
        progressBar.setMaximum(maxValue);
        progressBar.setStringPainted(true);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @param  state  DOCUMENT ME!
     */
    public void setProgressValue(final int state) {
        final Runnable r = new Runnable() {

                @Override
                public void run() {
                    progressBar.setValue(state);
                }
            };

        if (EventQueue.isDispatchThread()) {
            r.run();
        } else {
            EventQueue.invokeLater(r);
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @param  text  DOCUMENT ME!
     */
    public void setProgressText(final String text) {
        final Runnable r = new Runnable() {

                @Override
                public void run() {
                    progressBar.setString(text);
                }
            };

        if (EventQueue.isDispatchThread()) {
            r.run();
        } else {
            EventQueue.invokeLater(r);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        final java.awt.GridBagConstraints gridBagConstraints;

        progressBar = new javax.swing.JProgressBar();

        setLayout(new java.awt.GridBagLayout());

        progressBar.setIndeterminate(true);
        progressBar.setMaximumSize(new java.awt.Dimension(32767, 10));
        progressBar.setMinimumSize(new java.awt.Dimension(10, 10));
        progressBar.setPreferredSize(new java.awt.Dimension(200, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 330;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(progressBar, gridBagConstraints);
    } // </editor-fold>//GEN-END:initComponents
}
