/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.sudplan.wupp.objectrenderer;

import org.openide.util.NbBundle;

import de.cismet.cids.custom.sudplan.AbstractCidsBeanRenderer;
import de.cismet.cids.custom.sudplan.wupp.objecteditors.DeltaBreakingEdgeEditor.BEHeightConverter;
import de.cismet.cids.custom.sudplan.wupp.objecteditors.DeltaBreakingEdgeEditor.BETypeConverter;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  $Revision$, $Date$
 */
public class GeocpmBreakingEdgeRenderer extends AbstractCidsBeanRenderer {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXHyperlink hypConfig;
    private javax.swing.JLabel lblConfig;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblHeightValue;
    private javax.swing.JLabel lblIndex;
    private javax.swing.JLabel lblIndexValue;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblTypeValue;
    private javax.swing.JPanel pnlFill;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form GeocpmBreakingEdgeRenderer.
     */
    public GeocpmBreakingEdgeRenderer() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        lblIndex = new javax.swing.JLabel();
        lblIndexValue = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblTypeValue = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        lblHeightValue = new javax.swing.JLabel();
        lblConfig = new javax.swing.JLabel();
        hypConfig = new org.jdesktop.swingx.JXHyperlink();
        pnlFill = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        lblIndex.setText(NbBundle.getMessage(
                GeocpmBreakingEdgeRenderer.class,
                "GeocpmBreakingEdgeRenderer.lblIndex.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        add(lblIndex, gridBagConstraints);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${cidsBean.index}"),
                lblIndexValue,
                org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("<unreadable>");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblIndexValue, gridBagConstraints);

        lblType.setText(NbBundle.getMessage(
                GeocpmBreakingEdgeRenderer.class,
                "GeocpmBreakingEdgeRenderer.lblType.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        add(lblType, gridBagConstraints);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${cidsBean.type}"),
                lblTypeValue,
                org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("<unreadable>");
        binding.setConverter(new BETypeConverter());
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblTypeValue, gridBagConstraints);

        lblHeight.setText(NbBundle.getMessage(
                GeocpmBreakingEdgeRenderer.class,
                "GeocpmBreakingEdgeRenderer.lblHeight.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        add(lblHeight, gridBagConstraints);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${cidsBean.height}"),
                lblHeightValue,
                org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("<unreadable>");
        binding.setConverter(new BEHeightConverter());
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblHeightValue, gridBagConstraints);

        lblConfig.setText(NbBundle.getMessage(
                GeocpmBreakingEdgeRenderer.class,
                "GeocpmBreakingEdgeRenderer.lblConfig.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        add(lblConfig, gridBagConstraints);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${cidsBean.geocpm_configuration_id.name}"),
                hypConfig,
                org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue("<not set>");
        binding.setSourceUnreadableValue("<unreadable>");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(hypConfig, gridBagConstraints);

        pnlFill.setOpaque(false);

        final org.jdesktop.layout.GroupLayout pnlFillLayout = new org.jdesktop.layout.GroupLayout(pnlFill);
        pnlFill.setLayout(pnlFillLayout);
        pnlFillLayout.setHorizontalGroup(
            pnlFillLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(0, 410, Short.MAX_VALUE));
        pnlFillLayout.setVerticalGroup(
            pnlFillLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(0, 196, Short.MAX_VALUE));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        add(pnlFill, gridBagConstraints);

        bindingGroup.bind();
    } // </editor-fold>//GEN-END:initComponents

    @Override
    protected void init() {
        bindingGroup.unbind();
        bindingGroup.bind();
    }
}
